[package]
name = "marching-cubes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
bevy_flycam = { git = "https://github.com/sburris0/bevy_flycam" }
